// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcVojnik.Data;

namespace MvcVojnik.Migrations
{
    [DbContext(typeof(MvcVojnikContext))]
    partial class MvcVojnikContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcVojnik.Models.Vojnik", b =>
                {
                    b.Property<int>("VojnikId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Baza");

                    b.Property<DateTime>("DatumRođenja");

                    b.Property<string>("Ime");

                    b.Property<string>("Pozicija");

                    b.Property<string>("Prezime");

                    b.HasKey("VojnikId");

                    b.ToTable("Vojnik");
                });
#pragma warning restore 612, 618
        }
    }
}
